### ISSUE TITLE
Combine schema with optimist. Error on execution.

### ISSUE THREAD

**Issue by rcigni** [flatiron/prompt#164]
Hi!

I've tried to combine optimist and schema, but it doesn't work. Try this:

```javascript
var prompt = require('prompt'),
  optimist = require('optimist')

prompt.override = optimist.argv;

prompt.start();

var schema = {
  properties: {
    username: {
      required: true
    },
    email: {
      required: true
    }
  }
};

//
// Get two properties from the user: username and email
//
prompt.get(schema, ['username', 'email'], function (err, result) {
  console.log('Command-line input received:');
  console.log('  username: ' + result.username);
  console.log('  email: ' + result.email);
});
```
// TypeError: done is not a function
//   at /path/to/my/project/node_modules/prompt/lib/prompt.js:336:32
//   at /path/to/my/project/node_modules/async/lib/async.js:154:25
//   at assembler (/path/to/my/project/node_modules/prompt/lib/prompt.js:333:9)
//   at /path/to/my/project/node_modules/prompt/lib/prompt.js:342:32
//   at /path/to/my/project/node_modules/prompt/lib/prompt.js:625:5
//   at Interface.onLine (/path/to/my/project/node_modules/read/lib/read.js:111:5)
//   at emitOne (events.js:90:13)
//   at Interface.emit (events.js:182:7)
//   at Interface._onLine (readline.js:211:10)
//   at Interface._line (readline.js:550:8)

Am I missing something?
Thank you in advance, your lib is great for me.

**Comment by goatandsheep** [comment]
The readme [probably should not recommend optimist at all](https://www.npmjs.com/package/optimist), since the package is failing and has been deprecated and we should use [minimist](https://www.npmjs.com/package/minimist)
