### ISSUE TITLE
setMaxListeners issue with Node 0.11.13

### ISSUE THREAD

**Issue by smaxwellstewart** [flatiron/prompt#97]
Running this script produces the following error:

ERROR
```js
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at ReadStream.EventEmitter.addListener (events.js:179:15)
    at ReadStream.Readable.on (_stream_readable.js:667:33)
    at new Interface (readline.js:124:11)
    at Object.exports.createInterface (readline.js:38:10)
    at read (/home/kidtronnix/web/hapi-dash/node_modules/prompt/node_modules/read/lib/read.js:45:23)
    at EventEmitter.prompt.getInput (/home/kidtronnix/web/hapi-dash/node_modules/prompt/lib/prompt.js:502:3)
    at get (/home/kidtronnix/web/hapi-dash/node_modules/prompt/lib/prompt.js:321:12)
    at /home/kidtronnix/web/hapi-dash/node_modules/prompt/lib/prompt.js:280:7
    at iterate (/home/kidtronnix/web/hapi-dash/node_modules/prompt/node_modules/utile/node_modules/async/lib/async.js:134:13)
    at /home/kidtronnix/web/hapi-dash/node_modules/prompt/node_modules/utile/node_modules/async/lib/async.js:145:25

```
SCRIPT
```js
var prompt = require('prompt');
var fs = require('fs');

// Remove annoying "prompt:"
prompt.message = "";
prompt.delimiter = "";

var apiGenKey = function(length) {
    // Just produces random string using these chars
    var chars = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
    var result = '';
    for (var i = length; i > 0; --i) result += chars[Math.round(Math.random() * (chars.length - 1))];
    return result;
}


    

var messages = {
  app: "Configuring Basic App Info...\n".green,
  db: "Configuring MongoDB Connection...\n".green,
  api: "Configuring API Server...\n".green,
  gui: "Configuring GUI Server...\n".green,
  email: "Configuring Email app uses...\n".green,
}

// Define what we what entered
var schema = {
  properties: {
    appName: {
      description: messages.app+'App Name:'.blue,
      default: 'Hapi Dash'
    },
    appUrl: {
      description: 'App Url:'.blue,
      default: 'http://localhost:3030',
      before: function removeLastSlash (url) {
          if (url.substring(url.length-1) == "/")
          {
              url = url.substring(0, url.length-1);
          }

          return url;
      }
    },
    apiHost: {
      description: messages.api+'API host:'.blue,
      default: '127.0.0.1'
    },
    apiPort: {
      description: 'API port:'.blue,
      default: '3000'
    },
    apiCoreId: {
      description: 'API Core ID:'.blue,
      default: 'core'
    },
    apiCorePass: {
      description: 'API Core Password:'.blue,
      default: 'random string',
      before: function(value) {
        if(value === "random string") {
          value = apiGenKey(64)
        }
        return value;
      }
    },
    guiHost: {
      description:  messages.gui+'GUI host:'.blue,
      default: '0.0.0.0'
    },
    guiPort: {
      description: 'GUI port:'.blue,
      default: '3030'
    },
    dbHost: {
      description: messages.db+'Mongo host:'.blue,
      default: '127.0.0.1'
    },
    dbPort: {
      description: 'Mongo port:'.blue,
      default: '27017'
    },
    dbName: {
      description: "Mongo db name:".blue,
      default: 'hapi-dash'
    },
    mailService: {
      description: messages.email+'Email service:'.blue,
      default: 'Gmail'
    },
    mailEmail: {
      description: 'Email address:'.blue,
      required: true
    },
    mailPass: {
      description: 'Email password:'.blue,
      required: true,
      message: "Password is required",
      hidden: true
    },
  }
};
//
// Start the prompt
//
prompt.start();


prompt.get(schema, function (err, result) {
  //
  // Log the results.
  //
  if(result) {
    var config = {
      app: {
        name: result.appName,
        url: result.appUrl
      },
      db: {
        host: result.dbHost,
        port: result.dbPort,
        name: result.dbName
      },
      api: {
        host: result.apiHost,
        port: result.apiPort
      },
      coreCreds: {
          id: result.apiCoreId,
          key: result.apiCorePass,
          algorithm: 'sha256'
      },
      gui: {
        host: result.guiHost,
        port: result.guiPort
      },
      email: {
          service: result.mailService,
          auth: {
              user: result.mailEmail,
              pass: result.mailPass
          }
      }
    }

    // Text to save to config.js
    var text = "module.exports = "+JSON.stringify(config, null, 4)
    fs.exists('config.js', function (exists) {

      if(exists) {
        fs.renameSync('config.js', 'config.old.js')
        console.log('Backed up old config to config.old.js');
      } 

      fs.writeFile('config.js', text, function (err) {
        if (err) return console.log(err);
        console.log('Saved configuration: ', config);
      });
      
    });
  } else {
    console.log("\nAborted configuration!")
  }
  
});
```

**Comment by gangstead** [comment]
Your example works for me on node 5.5.0.  Closing as this is an old issue, but please reopen if you are still experiencing this problem on newer versions of node.

**Comment by Oipo** [comment]
@gangstead I experience this issue on node 5.10.0 with the following code: https://gist.github.com/Oipo/b179a5accb93b3c74ea52e6e806e4d37

I can't reopen this issue since I'm not the original creator.

**Comment by Oipo** [comment]
Sorry, am idiot. That while loop most definitely does not belong there.
